push_tutorials_to_website:
  stage: deploy_tutorials
  script:
    - cp tutorials/*.html /srv/manifesto-project.wzb.eu/public/down/tutorials/
    - cp tutorials/tutorials.json /srv/manifesto-project.wzb.eu/public/down/tutorials/
  only:
    - master
    - tutorials

stages:
  - build
  - deploy
  - deploy_tutorials
