# Scholarly Debate & Usage {#usage}

```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE, results='asis'}
library(RefManageR)
bib <- ReadZotero(group = "340777", .params=list())
WriteBib(bib, file="refs2.bib",note.replace.field="extra")

PrintBibliography(bib, .opts = list(style="markdown",bib.style="authoryear"))
```


This section presents a selection of scholarly work that made use of the manifesto dataset.
The literature can be categorized by the research design and the specific topic. 
First, this section separtes the huge amount of studies based on whether manifesto data is used as the dependent variable or as the independent variable. Is the goal of the research to explain why parties emphasize certain issues and take certain positions (manifesto as dependent variable) or is the goal to understand the consequences these emphases strategies and positions (independent variable). 

In a second step the research is categorized according to more specific topics. Each paper is summarized in  a single sentence.

NB: If you think that your research is missing here, please send me a link to your published article or chapter and attach your study as pdf document. You can also make a suggestion for the summarizing sentence. Please have in mind that we only review published studies here. 







## The Methodological Debate


* Summary of the methodological debate on Manifesto Project Data [@gemenis2013]
* Manifestos are expressions of a party's identity as well as of a party's image because they address voters and members alike [@harmel2016]
* Bayesian methods are superior to structural equation modeling when combining several sources of left-right positions to a common estimate [@bakker2009]
* continous measure of partisanship of government based on goverment composition data and manifesto data [@kim2002]
* median voter voter ideology [@kim2002]; continued by [@neve2011]
* The Manifesto Corpus is a new resource for research on political parties [@merz2016]
* strengths and weaknesses [@volkens2007]
* party positions based on manifesto data are highly valid [@budge2001]
* bara 2009 (social historical research)



### Critique: Document Selection

* The Danish part of the manifesto document collection is problematic because it is based on many substitute documents of varying length [@hansen2008]
* The use of substitute documents instead of electoral programs is problematic  [@gemenis2012]. Responses: [@benoit2012;@budge2012].


### critique - methodological discussion - Coding and Category Scheme

* The coding of natural sentences instead of quasi-sentences is equally reliable [@daubler2012] 
* Misclassification of codes is a serious and systemic problem with the current CMP data set and coding process [@mikhaylov2012]
* zulianello

### Scaling

#### Left-Right Positions
* rile
* [@klingemann1995]
* factor analysis [@gabel2000]
* laver garry
* kim fording
* lowe logratio
* Using different procedures to calculate left-right positions can produce substantively different results [@dinas2010]
* Categories can be better classified more fine-grained than dichotomously into left and right [@jahn2011]
* The different procedures of calculating left-right scores are based on different underlying assumptions [@franzmann2013]
* response by jahn [@jahn2014]
* Left-right positions according to the rile are not appropriate in Central and Eastern European countries [@molder2013]
* A naive iterative methodology to calculate left-right positions that puts emphasis on the importance of selecting the right (and left) categories [@prosser2014]
* elff
* mpp3

#### Issue emphasis


#### Uncertainty estimates

* Scholars should acknowledge measurement error in manifesto data and should use bootstrapped confidence intervals around estimates based on Manifesto Project Data [@benoit2009]
* Error estimates for the Manifesto Project Data can be calculated based on parties trajectories and some assumptions about parties behavior [@mcdonald2014]
* Uncertainty estimates based on two different approaches produce very similar results [@meyer2013]



### Validity 
Comparison with other measures

#### Comparisons of manifesto data and expert surveys
* There is some agreement but also numerous inconsistencies between expert survey data and manifesto data [@benoit2007-1]
* The associations between election rules and ideological congruence are relatively robust to various measurement approaches -- including Manifesto Project Data and expert surveys [@powell2009]
* Party positions based on expert surveys and manifestos are correlated [@hooghe2010]
* Using esimates based on different methodologies produces different results [@keman2007]
* Manifesto measures are error-prone for parties that are internally divided [@marks2007]
* Manifesto Project Data show more variance over time within parties than expert surveys [@mcdonald2007]
* Salience measures of european integration used in the Manifesto Project, European Election, and Expert surveys have a common structure. [@netjes2007]
* Substantive research results on EU politics are dependent on the choice of measurement indicators [@ray2007]


#### Comparisons of Manifesto Project Data and Computerized Scores

* budge pennings [@budge2007]
* response: [@benoit2007]
* re-response [@budge2007-2]
* Wordscores and Manifesto Project Data produce largely comparable data [@klemmensen2007].
* Computer coding can be used to locate weaknesses of Manifesto Project Data and the other way round [@pennings2011]
* Wordfish produces more plausible estimates for Japanese parties as the Manifesto Project Data because the documents are proxy documents [@proksch2011]



#### Comparisons with Media Data

* Issue positions of manifesto correlate with positions based on media data, but issue emphasis does not correlate [@helbling2011]
* There is an association between issue emphasis in media coverage and manifestos [@merz2016-1]


## Manifestos as dependent variable


### Public opinion

How do parties respond th changes in public opinion?

* Niche parties do not respond to shifts in public opinion, but mainstream parties do [@adams2006-1]
* Parties of the center and right react to both public opinion and the global economy, whereas parties of the left are not or less responsive [@adams2008]
* Mainstream parties respond to public opinion, niche parties to their supporters [@ezrow2011]
* opinion leaders [@adams2009-1]


### Time 

How have party strategies evolved over time?

* Parties talk about a growing number of issues, they are converging on the left–right scale, and the ideological cues they are sending to voters are increasingly ambiguous [@albright2010]
* Issue competition is becoming more important over the last decades while positional competition has lost some of its power [@green-pedersen2007]

### Electoral loss

* Parties shift their policies more when they have lost votes in the previous election than when they have gained votes; and the effect of past election results dissipates with the passage of time [@somer-topcu2009]

### Office aspiration/government experience

* Parties with low office aspiration shift their position more when they are in government than when they are in opposition [@schumacher2015-1]

### Competitors

* Mainstream parties emphasize anti-immigrant positions in response to radical right success, green party success have the opposite effect for the emphasis of environmental issues by mainstream parties [@abou-chadi2016-1] 


### Economy

* The more integrated an economy, the less differences between parties in terms of left-right positions [@steiner2012]
* Parties are less responsive in terms of their left-right positions in more open economics [@ezrow2014]
* Economc integration leads to convergence of party positions and increasing emphasis of non-economic issues [@ward2015]
* [@ward2011]


### Inequality
* greater income inequality under permissive electoral systems contributes to growing party polarisation [@han2015]
* [@pontusson2010]
* "supply-side constriction in the choices presented to voters, rather than the weakening of class divisions, accounts for the declining political relevance of redistributive values and the class basis of party choice." [@evans2012] check again for manifesto usage
* [@tavits2014-1]

### Decentralization
* Parties on the economic right are more supportive of decentralization than parties on the economic left, while culturally liberal parties favour decentralization more than culturally conservative parties [toubeau2015]

### Party competition
* When the number of parties in the system increases, the dispersion of parties also increases, but only up to a point [@andrews2009]

## Manifestos as independent variable

### Wage share of GDP
* When ideological centre in parliament shifts to the right, the wage share of GDP decreases [@wood2016]

### Globalization
* Leftist parties in government reduce the effect of globalization on income inequality [@ha2012].

### Satisfaction with democracy
* Citizen satisfaction increases when party choices in a political system are more ideologically proximate to the mean voter position in left–right terms [@ezrow2011-1]

### legitimacy
* [@anderson2012]

### Public Opinion

* whether climate change is a threat [@sohlberg2016]. 

### Perceived party positions

* Voters do not change their perceived positions of parties in line with parties' changes in left-right positions [@adams2011]
* Voters perceived positions of parties are not in line with parties' changes on the issue of European integration [@adams2014]
* Voters do change their perceived positions of parties in line with parties' changes in left-right positions [@fernandez-vazquez2014]


### Mass media

* Parties that emphasize certain issues are more often associated with these issues in media coverage [@merz2016-1].

### Electoral success

* Parties loose votes when they change their position on principle issues [@tavits2007]
* Niche parties loose when they moderate their left-right position [@adams2006-1]
* Parties gain votes at the current election when they moderated their policies at the previous election [@adams2009]

### Coalition formation

* Parties that emphasize themes in their election manifestos that correspond to the policy remit of specific cabinet portfolios are more likely to obtain control over these portfolios [@back2011-1]
* Programmatic similarity index explains coalition formation better than other indicators of policy differences [molder2016]


### Policy making

* Governmental parties having pro-environmentalist policy positions adopt more environmental measures  [@knill2010]
* Green tax burdens are influenced by the left–right and environmental positions of legislative medians  [@ward2012]

### Government sSpending

* Parties emphasizing certain issues areas in their program spend more on these when in power [@budge1990]
* Association between parties' issue emphasis in electoral programs and government spending  [@klingemann1994] -- debated in [@king1993]
* Shifts in Italian government's issue emphasis can explain changes in welfare and defence spending, but not in spendings on public order and education [@russo2016]
* An analysis of determinants of the gap between parties' emphasis of welfare issues and welfare spending  [@horn2016]
* Party ideology does not influence education spending [@garritzmann2015]
* Parties that emphasize law and order in their program spend more on public order and safety if there is room to manœuvre [@wenzelburger2015-1]
* Government ideology, measured as welfare and international positions, affects defense spending -- conditional on the international security environment [@whitten2011-1]

### Foreign affairs

* Left parties in government contribute more to NATO's military intervention in Lybia [@haesebrouck2016]
* Parties that emphasize concepts related to militarism relative to anti-militarism and pacifism are more likely to initiate conflicts [@heffington2016]
* Government ideology has no effect on establishment/strength of diplomatic relationships with North Korea [@onderco2015]
* Partisanship has no effect on participation in air strikes against IS [@haesebrouck2016-1]

\nocite{*}
