# The Manifesto Project Dataset {#maindataset}

## Access

The Manifesto Project Dataset can be accessed in different ways:

* The dataset can be downloaded from the [Manifesto Project Website](https://manifesto-project.wzb.eu/datasets). To be able to download the dataset, you need to login on the website. Login is possible after having registered. Registration is free, simple and quick. The dataset is available in different formats: 
    * .xlsx for [Excel](https://products.office.com/de-de/excel),
    * .dta for [Stata](http://www.stata.com/) (version 13 and 14), 
    * .sav for [SPSS](https://www-01.ibm.com/software/de/analytics/spss/), 
    * .csv as  [comma-separated values](https://en.wikipedia.org/wiki/Comma-separated_values).

* The dataset can be [browsed  online](https://visuals.manifesto-project.wzb.eu/mpdb-shiny/cmp_dashboard_dataset/). The online dashboard is convenient for simple analysis, but does not offer the same analytical possibilites as a statistical software packages such as R, Stata or SPSS.

* The dataset can be accessed directly in R and Stata using the add-ons [manifestoR](#manifestoR-ds) and [manifestata](#manifestata-ds).


## Data set structure and variables

Each row in the dataset represents one electoral program. **The variables party and date uniquely identify every row in the dataset.**


### Identification variables

The *country* variable is 2 or 3 digit code that identifies the country. The codes follow a loose systematic where:

* 1x: Nordic countries (11 Sweden, 12, Norway, 13 Denmark, 14, Finland, 15 Iceland)
* 2x: Benelux countries (21 Belgium, 22, Netherlands, 23 Luxembourg)
* 3x: South/West European countries (31 France, 32 Italy, 33 Spain, 34 Greece, 35 Portugal)
* 4x: (Partially) German speaking countries (41 Germany, 42, Austria, 43, Switzerland)
* 5x: Islands (51 UK, 52, Northern Ireland, 53, Ireland, 54 Malta, 55 Cyprus)
* 6x: English speaking countries oversea (61 United States, 62 Canada, 63 Australia, 64 New Zealand)
* 7x,8x,9x,1xx: other (mostly) OECD and Central/Eastern European countries (71 Japan, 72 Israel, 73 Sri Lanka, 74, Turkey, 75 Albania, 76 Armenia, 77 Azerbaijan, 78 Belarus, 79 Bosnia-Herzegovina, 80 Bulgaria, 81, Croatia, 82 Czech Republic, 83, Estonia, 84 Georgia, 85 Germand Democratic Republic, 86 Hungary, 87 Latvia, 88 Lithuania, 89 Macedonia, 90 Moldova, 91 Montenegro, 92 Poland, 93 Romania, 94 Russia, 95 Serbia, 96 Slovakia, 97 Slovenia, 98 Ukraine, 113 South Korea, 171 Mexico)

The *countryname* indicates the name of the country as a character variable.

The variables *oecdmember* and *eumember* indicate whether a country was a full member (coded as 10) of the OECD or of the EU at the time of the election, not a member at all (coded as 0) or (in case of the EU) an applicant  (20). 

*edate* contains information on the day of the election encoded in the specific date-time format.

*date* is a six-digit number that indicates the year and month of the respective national election in the format YYYYMM, e.g. 201102 indicates an election in February 2011.

The *party* variable is a 5 or 6 digit code that identifies every party in the dataset.

*partyname* is the (translated) English name of the party.

*partyabbrev* is the original language abbreviation of the party (in latin alphabet) as long as there is an official or popular abbreviation.

*parfam* indicates the party family of the 

| code | party family |
|------|--------------|
| 10 | Ecological parties|
| 20 | Socialist parties |
| 30 | Social democratic parties |
| 40 | Liberal parties| 
| 50 | Christian democratic parties |
| 60 | Conservative parties |
| 70 | Nationalist parties |
| 80 | Agrarian parties | 
| 90 | Ethnic and regional parties |
| 95 | Special issue parties |
| 98 | Electoral alliances of diverse origin without dominant party |
| 999 | Missing information|


The dataset contains four variables related to the coding process. 

The *coderid* is a unique identifier for every coder. 

The *manual variable* indicates the version of the coding instructions with which the coding took place (see [here](#versions) for why there are different versions).

The *testresult* variable indicates the result of the reliability score of the [entry test of the coder](#training). 

The *testeditsim* is another measure of reliability of the coders' entry test result. 


### electoral statistics

*pervote* variable indicates the 

* voteest
* presvote
* absseat
* totseats



### Manifesto variables

In a perfect world, each party would publish a manifesto for every election. Unfortunately, that is not always the case as sometimes parties do not publish a manifesto at all, or publish a joint manifesto together with other parties, etc. The *progtype* tries to capture the diversity with the source documents.


- *1: Program of a single party*. As a rule, each party issues one program for each election. 
- *2: Program of two or more parties*. In a number of countries, parties compete as programmatic coalitions by issuing joint programs. In these cases, the joint program were assigned to every party in the programmatic
coalition.
- *3: Missing program with approximated data*. Missing election programs were approximated on the basis of available programs. Estimates were derived either by computing averages between two adjacent programs or by duplicating programmatic data
- *4: Program taken from main party of electoral coalition*. In CEE countries parties often compete as electoral coalitions in which blocs of parties receive joint votes and seats even though parties in the bloc still issue separate programs. When the electoral coalition is dominated by one strong party, the program of the main coalition party was used to measure positions of the ‘electoral coalition’ as a whole. 
- *5: Average of all members of an electoral coalition*. When the electoral coalition consists of equally strong parties the average of platforms from all coalition parties was used to measure positions of the electoral coalition as a whole
- *6: General program*. Some parties did not issue separate election programs but took part in elections with their general programs.
- *8: Party bloc program. Some party blocs issue joint programs. As opposed to type 2 programs, electoral statistics are given for the party bloc as a whole, not for the single parties comprising the bloc.
- *9: Other program type.* Other types of programs not specified by types 1 to 8.
- *99: Missing program (not approximated by other data).* In cases where it was impossible to find a manifesto from the respective party or in cases where content-analytical data from this party is still missing, but will be added soon.


datasetorigin

corpusversion

### Coding variables (per*-variables)

The *total* variable indicates the total number of quasi-sentences in the manifesto. 

The dataset contains three sets of content analytical variables (*per101-706*; *per1011-7062*; *per103_1-703_2*). All of these variables indicate the share of quasi-sentences in the respective category calculated as a fraction of the overall number of allocated codes per document

* The three digit variables *(per101–per706)* are the main categories of the coding scheme
* The four digit variables *(per1011-per7062)* are sub-categories mostly addressing issues in transitional democracies in (mostly) Central and Eastern European countries. However, they were introduced in version one of the coding instructions and were gradually abandoned in most of the countries as the issues could also be coded into the three digit main categories. Currently, the share of these categories is not included in the main categories. If analysts use observations from CEE countries for which the CEE codes were used and want to compare them to manifestos without CEE codes then they should aggregate such CEE codes into the main categories.
* The four digit variables with underscore *(per103_1-703_2)* are new categories introduced with version 5 of the coding instructions. The first three digits indicate the main category to which they are related. The new coding instructions tell users to utilise these new subcategories rather than the respective main categories.  Currently, the new categories are aggregated into the main categories to ensure over-time comparability of the main categories. The only exception to this aggregation are categories 202_2, 605_2 and 703_2, which have to be added to the uncoded sentences, as such issues were not covered in the handbook4 category scheme. For this reason these sentences were previously coded as 000. So, scholars interested in long-time series can simply continue to use the existing main categories (per101-706, including e.g. the rile) as they did in the past and ignore the new categories. Scholars interested in the new categories should be aware that the respective main categories of the new sub- categories are aggregates of the new categories (i.e. if one uses the main categories together with the new subcategories the per-variables will likely add up to more than 100%).

For more information on the different version of the coding instructions
and coding schemes, please consult the [website where one can find all
versions of the coding instructions](https://manifesto-project.wzb.eu/information/documents/handbooks) and a document that highlights the
most important changes between them.



### Aggregate indices


### Dataset version



## manifestoR & manifestata {#manifestoR-ds}

## Different measures of...

### Issue emphasis

### Calculating Left-Right Positions

#### rile

#### kim fording

#### vanilla

#### log ratio

#### franzmann kaiser

#### jahn

[@jahn2011]

### uncertainty estimates

#### blm

#### mcdonald budge

### More measures

#### effect number of issues

#### niche measures

#### clarity


