# The Manifesto Corpus {#corpus}

## Access the Manifesto Corpus

## ... using manifestoR {#manifestoR}

### tm corpus format

### quanteda corpus format

### tidytext format

The tidy text format is inspired by the tidy data format [@wickham2014]. Data is tidy if

- each variable is a column
- each observation is a row
- each type of observational unit is a table

The tidy text format picks up these three principles. Tidy text is format where information is stored in a table 
 "table with one-token-per-row" [@silge2016]. This is in contrast to the idea of term-document or document-feature matrices.

The advantage of the tidy text format is that it allows users the user of many R operations that are known from other data manipulation and data management tasks.

The tidytext package provides functions to transform several other data formats into a tidy text format. 
These functions can also be applied to the Manifesto Corpus format.

```{r chunk-labele, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, collapse=TRUE, warnings=FALSE}
library(tidytext)
de2013 <- de %>%
   tidy() %>% unnest_tokens(text,text) %>% select(party,text)

knitr::kable(
  head(de2013), caption="TESt"
)
```


### key word search 

library(manifestoR)
library(tidyverse)
library(tidytext)

mp_setapikey(key.file="manifesto_apikey.txt")
mp_use_corpus_version("2016-6")

dictionary <- tibble(word=c("war","peace"))

dict_counts <- mp_corpus(country== 61 | country == 51) %>% 
   tidy() %>% 
   group_by(party,date) %>%
   unnest_tokens(word,text,token="words", to_lower=TRUE) %>%
   inner_join(dictionary) %>%
   count(word, sort=TRUE)

   
### term frequency


## ... using manifestata

