install.packages("manifestoR", repos="https://cloud.r-project.org")
install.packages("bookdown", repos="https://cloud.r-project.org")
install.packages("labelled", repos="https://cloud.r-project.org")
install.packages("jsonlite", repos="https://cloud.r-project.org")
install.packages("formatR", repos="https://cloud.r-project.org")
library(jsonlite)
library(httr)
library(manifestoR)
library(bookdown)
library(rmarkdown)
library(shiny)

mp_setapikey(key.file = "manifesto_apikey.txt")
render_site(output_format = "bookdown::gitbook", encoding = "UTF-8")
